In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("mental_health_risk_dataset (1).csv")
print("Shape",df.shape)

Shape (25000, 25)

In [18]:
print(df.shape)

(25000, 25)

In [2]:
df.head()

,age,gender,marital_status,education_level,employment_status,sleep_hours,physical_activity_hours_per_week,screen_time_hours_per_day,social_support_score,work_stress_level,...,depression_score,stress_level,mood_swings_frequency,concentration_difficulty_level,panic_attack_history,family_history_mental_illness,previous_mental_health_diagnosis,therapy_history,substance_use,mental_health_risk
0,56,Other,Single,Bachelor,Unemployed,8.6,2.8,9.6,7,10,...,4,8,8,3,1,0,1,1,1,1
1,47,Male,Single,Bachelor,Unemployed,4.5,2.7,3.0,10,6,...,7,4,9,3,0,0,0,0,0,0
2,56,Female,Divorced,Bachelor,Student,3.1,14.1,7.2,10,5,...,3,1,4,2,1,1,1,1,1,2
3,59,Other,Married,Bachelor,Employed,7.0,0.5,10.3,2,10,...,8,5,2,5,1,1,0,1,1,2
4,58,Male,Single,High School,Self-Employed,5.1,2.5,1.2,8,1,...,8,3,3,1,0,0,1,0,1,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 25 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   age                               25000 non-null  int64
 1   gender                            25000 non-null  object
 2   marital_status                    25000 non-null  object
 3   education_level                   25000 non-null  object
 4   employment_status                 25000 non-null  object
 5   sleep_hours                       25000 non-null  float64
 6   physical_activity_hours_per_week  25000 non-null  float64
 7   screen_time_hours_per_day         25000 non-null  float64
 8   social_support_score              25000 non-null  int64
 9   work_stress_level                 25000 non-null  int64
 10  academic_pressure_level           25000 non-null  int64
 11  job_satisfaction_score            25000 non-null  int64
 12  financial_stress_level            25000 non-null  int64
 13  working_hours_per_week            25000 non-null  int64
 14  anxiety_score                     25000 non-null  int64
 15  depression_score                  25000 non-null  int64
 16  stress_level                      25000 non-null  int64
 17  mood_swings_frequency             25000 non-null  int64
 18  concentration_difficulty_level    25000 non-null  int64
 19  panic_attack_history              25000 non-null  int64
 20  family_history_mental_illness     25000 non-null  int64
 21  previous_mental_health_diagnosis  25000 non-null  int64
 22  therapy_history                   25000 non-null  int64
 23  substance_use                     25000 non-null  int64
 24  mental_health_risk                25000 non-null  int64
dtypes: float64(3), int64(18), object(4)
memory usage: 4.8+ MB

In [4]:
df.describe()

,age,sleep_hours,physical_activity_hours_per_week,screen_time_hours_per_day,social_support_score,work_stress_level,academic_pressure_level,job_satisfaction_score,financial_stress_level,working_hours_per_week,...,depression_score,stress_level,mood_swings_frequency,concentration_difficulty_level,panic_attack_history,family_history_mental_illness,previous_mental_health_diagnosis,therapy_history,substance_use,mental_health_risk
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,...,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,39.072560,6.509516,7.515400,6.469132,5.50840,5.517080,5.445880,5.471040,5.495080,45.049600,...,5.534000,5.520480,5.512880,5.488240,0.497840,0.504280,0.504160,0.501640,0.499120,0.778520
std,12.404948,2.015586,4.324346,3.167682,2.88694,2.864548,2.864479,2.867816,2.881636,14.683297,...,2.870048,2.873213,2.870596,2.873178,0.500005,0.499992,0.499993,0.500007,0.500009,0.691409
min,18.000000,3.000000,0.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,20.000000,...,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28.000000,4.800000,3.800000,3.700000,3.00000,3.000000,3.000000,3.000000,3.000000,32.000000,...,3.000000,3.000000,3.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,39.000000,6.500000,7.500000,6.500000,5.00000,6.000000,5.000000,5.000000,5.000000,45.000000,...,6.000000,6.000000,6.000000,5.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000
75%,50.000000,8.200000,11.300000,9.200000,8.00000,8.000000,8.000000,8.000000,8.000000,58.000000,...,8.000000,8.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,60.000000,10.000000,15.000000,12.000000,10.00000,10.000000,10.000000,10.000000,10.000000,70.000000,...,10.000000,10.000000,10.000000,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000

In [5]:
print(df.isnull().sum())

age                                 0
gender                              0
marital_status                      0
education_level                     0
employment_status                   0
sleep_hours                         0
physical_activity_hours_per_week    0
screen_time_hours_per_day           0
social_support_score                0
work_stress_level                   0
academic_pressure_level             0
job_satisfaction_score              0
financial_stress_level              0
working_hours_per_week              0
anxiety_score                       0
depression_score                    0
stress_level                        0
mood_swings_frequency               0
concentration_difficulty_level      0
panic_attack_history                0
family_history_mental_illness       0
previous_mental_health_diagnosis    0
therapy_history                     0
substance_use                       0
mental_health_risk                  0
dtype: int64

In [6]:
print(df['mental_health_risk'].value_counts())
print("\nAs percentages:")
print(df['mental_health_risk'].value_counts(normalize=True).round(2) * 100)

mental_health_risk
1    11823
0     9357
2     3820
Name: count, dtype: int64

As percentages:
mental_health_risk
1    47.0
0    37.0
2    15.0
Name: proportion, dtype: float64

DATASET OVERVIEW
- Total records: 25,000
- Total features: 24
- Target variable: mental_health_risk (0 = low, 1 = medium, 2 = high)
- Missing values: None
CLASS DISTRIBUTION
- Class 0 (Low Risk): 37%
- Class 1 (Medium Risk): 47X%
- Class 2 (High Risk): 15%

KEY OBSERVATION
The dataset is imbalanced — class 2 has significantly fewer samples than 
classes 0 and 1. This means accuracy alone will be a misleading metric. 
We will use precision, recall, and F1-score instead.

In [10]:
import os
print(os.path.exists(r"C:\Users\PURBA CHOUDHURY\Mental-Health-Risk-Classifier\MHRCdataExploration.ipynb"))

False